const SKILLS_BY_DEPARTMENT = {
  "B.Sc.IT": [
    "JavaScript",
    "React",
    "Node.js",
    "MongoDB",
    "SQL",
    "Python",
    "Java",
    "DSA",
    "OOP",
    "REST APIs",
  ],
  "B.Sc.DS": [
    "Python",
    "Deep Learning",
    "Machine Learning",
    "Data Analysis",
    "TensorFlow",
    "Pandas",
    "NumPy",
    "SQL",
    "Tableau",
    "Statistics",
  ],
  "B.Sc.AI/ML": [
    "Python",
    "RAG Models",
    "GenAI",
    "Deep Learning",
    "Machine Learning",
    "Data Analysis",
    "TensorFlow",
    "Pandas",
    "NumPy",
    "SQL",
    "Tableau",
    "Statistics",
  ],

  "B.B.A": [
    "Business Strategy",
    "Marketing",
    "HR Management",
    "Operations",
    "Communication",
    "Leadership",
  ],

  "B.F.A": [
    "Excel",
    "Financial Analysis",
    "Accounting",
    "Tax Planning",
    "Investment Analysis",
    "Risk Management",
  ],
  "B.F.M": [
    "Excel",
    "Financial Analysis",
    "Accounting",
    "Tax Planning",
    "Investment Analysis",
    "Risk Management",
  ],
  "B.A.D.M.C": [
    "Business Strategy",
    "Marketing",
    "HR Management",
    "Operations",
    "Communication",
    "Leadership",
  ],
  "B.A.F": [
    "Excel",
    "Financial Analysis",
    "Accounting",
    "Tax Planning",
    "Investment Analysis",
    "Risk Management",
  ],
  "B.F.M": [
    "Excel",
    "Financial Analysis",
    "Accounting",
    "Tax Planning",
    "Investment Analysis",
    "Risk Management",
  ],
  "B.M.S": [
    "Business Strategy",
    "Marketing",
    "HR Management",
    "Operations",
    "Communication",
    "Leadership",
  ],
  "B.B.I": [
    "Business Strategy",
    "Marketing",
    "HR Management",
    "Operations",
    "Communication",
    "Leadership",
  ],
  "B.A.M.M.C": [
    "Business Strategy",
    "Marketing",
    "HR Management",
    "Operations",
    "Communication",
    "Leadership",
  ],
  "M.Sc.IT": [
    "JavaScript",
    "React",
    "Node.js",
    "MongoDB",
    "SQL",
    "Python",
    "Java",
    "DSA",
    "OOP",
    "REST APIs",
  ],
  "M.Sc.AI/DS": [
    "Python",
    "RAG Models",
    "GenAI",
    "Deep Learning",
    "Machine Learning",
    "Data Analysis",
    "TensorFlow",
    "Pandas",
    "NumPy",
    "SQL",
    "Tableau",
    "Statistics",
  ],
  "M.Sc.CyberSecurity": [
    "Network Security",
    "Cryptography",
    "Ethical Hacking",
    "Risk Assessment",
    "Incident Response",
  ],
  "M.Com(AA)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
  "M.Com(B&A)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
  "M.Com(B&F)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
  "M.Com(BM)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
  "M.A.(EMA)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
};

export default SKILLS_BY_DEPARTMENT;
